ignore machete to make ci pass.
Check unused dependencies

Run cargo machete
Analyzing dependencies of crates in this directory...
cargo-machete found the following unused dependencies in this directory:
registry -- ./registry/Cargo.toml:
	mockall
shared -- ./shared/Cargo.toml:
	secrecy
kernel -- ./kernel/Cargo.toml:
	chrono
	derive-new
	mockall
	strum
api -- ./api/Cargo.toml:
	axum-extra
	chrono
	derive-new
	garde
	strum
	tokio
	tokio-stream
	tower
	tracing
	utoipa
adapter -- ./adapter/Cargo.toml:
	chrono
	secrecy
Done!
rusty-book-manager -- ./Cargo.toml:
	opentelemetry
	opentelemetry-jaeger
	tracing-opentelemetry
	utoipa
	utoipa-redoc

If you believe cargo-machete has detected an unused dependency incorrectly,
you can add the dependency to the list of dependencies to ignore in the
`[package.metadata.cargo-machete]` section of the appropriate Cargo.toml.
For example:

[package.metadata.cargo-machete]
ignored = ["prost"]

You can also try running it with the `--with-metadata` flag for better accuracy,
though this may modify your Cargo.lock files.

Error: Process completed with exit code 1.